main{
    topBar{
        logo
        searchBar
      }
    sideBar{
		weeklyInfo{
        	title
        	weeklyInfoContainer{
        	    dayName
        	    weatherIcon
        	    temp{
        	        high
        	        low
        	      }
        	  }
		}
      }
    mainInfo {
        currentInfo{
            cityName
            timeDay{
                weekday
                currentTime
              }
            weatherIcon
            temp
            smallText{
                high
                low
                weatherType
              }

          }
        hourlyInfo{
            hourlyContainer{
                time
                weatherIcon
                temp
              }
          }
        otherInfo{
            otherInfoContainer{
                title
                info
              }
          }
      }
  }